apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eo55jlgpl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eo55jlgpl-python 
  name: eo55jlgpl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eo55jlgpl-python 
